name = "blog-oauth"
main = "src/index.js"
compatibility_date = "2023-12-24"

[vars]
GITHUB_CLIENT_ID = "Ov23lidgLe1RzdUISJ2R"

# 在 Cloudflare Dashboard 中设置这个密钥
# GITHUB_CLIENT_SECRET = "57f7add2e7d91efd06eef9ee99bea8ef35ff05cf"

[[routes]]
pattern = "auth.my-blog-helpfulcraft.pages.dev"
custom_domain = true
